### ISSUE TITLE
Kit editor window is miniscule and can't be resized on Ubuntu Linux

### ISSUE THREAD

**Issue by jhob101** [jkotlinski/lsdpatch#99] opened 2024-09-15 15:48 UTC
When opening the Kit Editor window it opens at the smallest possible size - see screenshot below, the kit editor window is the one to the right of main window.

![2024-09-15_16-37](https://github.com/user-attachments/assets/059dd9ff-8b19-4a6e-99ef-113f2031cc00)

It can't be resized.  All other windows open fine.

Zorin OS 17.1 (Ubuntu 22.04)
LSDPatcher 1.13.1
JRE 2:1.11-72build2

**Comment by defensem3ch** [comment] 2024-09-15 18:46
i also get this issue on linux mint. the only workaround i'm aware of is to close the window and reopen until eventually it will open at the proper size.

**Comment by jhob101** [comment] 2024-09-16 10:00
I have also tested this in Kubuntu 24.04 and the issue is also present there.

I note that in a Windows VM the kits window appears to animate expanding (very quickly) from the top left corner.  I wonder if that animation was disabled whether it might then work?

**Comment by jkotlinski** [comment] 2024-09-17 18:24
Should be fixed now. Thanks for reporting!

**Comment by defensem3ch** [comment] 2024-09-17 21:57
i'm still getting this issue - happens after closing kit editor and reopening a few times

**Comment by jhob101** [comment] 2024-09-18 10:59
Will there be a new release incorporating this fix or do I need to build it?

**Comment by jkotlinski** [comment] 2024-09-18 15:37
Uh oh! I just released 1.13.2 with a fix. But now I read that the problem is still there! Not good, I will have to investigate further.

**Comment by jhob101** [comment] 2024-09-19 09:31
Yep, I can confirm not fixed I'm afraid.  Thank you for looking in it :)

**Comment by jkotlinski** [comment] 2024-09-19 18:55
OK, I made another fix now (not released yet)! I hope it works better. I tried reopening the kit editor well over 10 times, and no problem.

**Comment by defensem3ch** [comment] 2024-09-20 14:44
confirmed to be fixed here!

**Comment by jkotlinski** [comment] 2024-09-20 18:21
released as 1.13.3, thank you for the help!

**Closed by jkotlinski** 2024-09-20 18:21 UTC

**Comment by jhob101** [comment] 2024-09-23 09:11
Confirmed fixed here too - many thanks!
